= Deployment bundle `configs`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Initial commit
:doctype: article
// Visual
:toc: macro
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:lsb: [
:rsb: ]
:url_dd: https://github.com/divine-dotfiles/divine-dotfiles

++++
<p align="center">
<em>A deployment bundle for <a href="https://github.com/divine-dotfiles/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

The deployment bundle `configs` is under development.

// TODO

[[bundle-main]]
== Description

// TODO

[[inun-main]]
== Installing and uninstalling the bundle

// TODO

[[dpls-main]]
== Bundled deployments

:leveloffset: 2

# Divine bundle '*config-hyperjs*'
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Initial commit
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

++++
<p align="center">
<em>A deployment bundle for <a href="https://github.com/divine-dotfiles/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

## Description

Divine bundle '*config-hyperjs*' maintains your personal configuration file for https://hyper.is[Hyper.js].

[.note]
[%noheader,cols="<.<a"]
|===
| This deployment provides useful default version of configuration file.
Look for it in `~/.grail/assets/config-hyperjs`.
|===

## Installation/removal

Install via any Terminal.

[.note]
[%noheader,cols="<.<a"]
|===
| Pre-existing configuration file, if any, will be moved to backup directory and restored upon removal.
|===

### Don't have Divine.dotfiles installed?

*Install both framework & this deployment* in one fell swoop (it's fully removable):

[source,bash]
----
bash -c "TMP=\$(mktemp); URL=https:\
//raw.github.com/divine-dotfiles/divine-dotfiles/master/lib/install/install.sh\
; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --ver\
sion &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fa\
iled to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf \
>&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach config-hyperjs --yes \
&& ~/.divine/intervene.sh install --yes
----

Afterward, if you don't like it, here is the '**undo**' command (removes/restores _everything_):

[source,bash]
----
~/.divine/intervene.sh remove --yes \
&& ~/.divine/intervene.sh detach config-hyperjs --yes \
&& bash -c "TMP=\$(mktemp); URL=https://raw.\
github.com/divine-dotfiles/divine-dotfiles/master/lib/uninstall/uninstall.sh; \
if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --versi\
on &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fail\
ed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf >&\
2 \"\n==> Error: failed to download uninstallation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes
----

### Already a Divine.dotfiles user?

Attach this deployment to your copy of Divine.dotfiles as such:

[source,bash]
----
di attach config-hyperjs --yes
----

Then install as usual.

If ever removing this deployment, make sure you uninstall it first, and then:

[source,bash]
----
di detach config-hyperjs --yes
----

:leveloffset!:

:leveloffset: 2

# Divine bundle '*config-transmissionbt*'
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Initial commit
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

++++
<p align="center">
<em>A deployment bundle for <a href="https://github.com/divine-dotfiles/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

## Description

Divine bundle '*config-transmissionbt*' maintains your personal configuration file for https://transmissionbt.com[Transmission BitTorrent Client].

[.note]
[%noheader,cols="<.<a"]
|===
| Look for instructions for storing your Transmission configuration file at `~/.grail/assets/config-transmissionbt`.
|===

## Installation/removal

Install via any Terminal.

[.note]
[%noheader,cols="<.<a"]
|===
| Pre-existing configuration file, if any, will be moved to backup directory and restored upon removal.
|===

### Don't have Divine.dotfiles installed?

*Install both framework & this deployment* in one fell swoop (it's fully removable):

[source,bash]
----
bash -c "TMP=\$(mktemp); URL=https:\
//raw.github.com/divine-dotfiles/divine-dotfiles/master/lib/install/install.sh\
; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --ver\
sion &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fa\
iled to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf \
>&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach config-transmissionbt --yes \
&& ~/.divine/intervene.sh install --yes
----

Afterward, if you don't like it, here is the '**undo**' command (removes/restores _everything_):

[source,bash]
----
~/.divine/intervene.sh remove --yes \
&& ~/.divine/intervene.sh detach config-transmissionbt --yes \
&& bash -c "TMP=\$(mktemp); URL=https://raw.\
github.com/divine-dotfiles/divine-dotfiles/master/lib/uninstall/uninstall.sh; \
if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --versi\
on &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fail\
ed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf >&\
2 \"\n==> Error: failed to download uninstallation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes
----

### Already a Divine.dotfiles user?

Attach this deployment to your copy of Divine.dotfiles as such:

[source,bash]
----
di attach config-transmissionbt --yes
----

Then install as usual.

If ever removing this deployment, make sure you uninstall it first, and then:

[source,bash]
----
di detach config-transmissionbt --yes
----

:leveloffset!:

:leveloffset: 2

# Divine bundle '*config-vscode*'
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Initial commit
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

++++
<p align="center">
<em>A deployment bundle for <a href="https://github.com/divine-dotfiles/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

## Description

Divine bundle '*config-vscode*' maintains your personal configuration file for https://code.visualstudio.com[Visual Studio Code].

[.note]
[%noheader,cols="<.<a"]
|===
| This deployment provides useful default version of configuration file.
Look for it in `~/.grail/assets/config-vscode`.
|===

## Installation/removal

Install via any Terminal.

[.note]
[%noheader,cols="<.<a"]
|===
| Pre-existing configuration file, if any, will be moved to backup directory and restored upon removal.
|===

### Don't have Divine.dotfiles installed?

*Install both framework & this deployment* in one fell swoop (it's fully removable):

[source,bash]
----
bash -c "TMP=\$(mktemp); URL=https:\
//raw.github.com/divine-dotfiles/divine-dotfiles/master/lib/install/install.sh\
; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --ver\
sion &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fa\
iled to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf \
>&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach config-vscode --yes \
&& ~/.divine/intervene.sh install --yes
----

Afterward, if you don't like it, here is the '**undo**' command (removes/restores _everything_):

[source,bash]
----
~/.divine/intervene.sh remove --yes \
&& ~/.divine/intervene.sh detach config-vscode --yes \
&& bash -c "TMP=\$(mktemp); URL=https://raw.\
github.com/divine-dotfiles/divine-dotfiles/master/lib/uninstall/uninstall.sh; \
if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget --versi\
on &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Error: fail\
ed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { printf >&\
2 \"\n==> Error: failed to download uninstallation script\n\"; rm -f \$TMP; ex\
it 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && exit \
3 || exit 0" bash --yes
----

### Already a Divine.dotfiles user?

Attach this deployment to your copy of Divine.dotfiles as such:

[source,bash]
----
di attach config-vscode --yes
----

Then install as usual.

If ever removing this deployment, make sure you uninstall it first, and then:

[source,bash]
----
di detach config-vscode --yes
----

:leveloffset!: